import Head from "next/head";
import PosterSlider from "../../components/utils/PosterSlider";
import { getCollectionByID } from "../../helpers/collectionApiCalls";
import ActionBlock from "../../components/utils/ActionBlock";
import {shorten, withAuth} from "../../helpers/utilities";

export async function getServerSideProps({ query }) {
    return getCollectionByID(query.collectionID).then(hero => {
        if (!hero || hero.error) {
            return {
                notFound: true,
            }
        }
        return {props: {hero}}
    })
}

const collection = ({ hero }) => {

    return (
        <div>
            <Head>
                <title>HERA | {hero.name}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div id="hero" className="hero" style={{backgroundImage: `url(${hero.background_image})`}}>
                <section/>
                <div className="hero_content">
                    <p className="hero_supertitle">MOVIE COLLECTION</p>
                    <h2 className="hero_title">{hero.name && hero.name.toUpperCase()}</h2>

                    <p className="hero_description">{shorten(hero.description)}</p>

                    <ActionBlock media={hero.parts[0]} type="collection"/>

                    <div className="hero_parts">
                        <PosterSlider medias={hero.parts} preload={true} />
                    </div>
                </div>
            </div>
        </div>
    )
}

export default withAuth(collection)