import {useEffect, useState} from "react"
import {getAllCollections, getRandomCollection} from "../../helpers/collectionApiCalls"
import MediaSlider from "../../components/utils/MediaSlider"
import Head from "next/head"
import PosterSlider from "../../components/utils/PosterSlider"
import ActionBlock from "../../components/utils/ActionBlock";
import {shorten, withAuth} from "../../helpers/utilities";
import Fallback from "../../components/Fallback";
import {ErrorBoundary} from "react-error-boundary";

const Home = () => {

    const [collections, setCollections] = useState([])
    const [hero, setHero] = useState(null)

    const preload = () => {
        getRandomCollection().then(data => {
            setHero(data)
        })
        getAllCollections().then((data) => {
            setCollections(data)
        }).catch(err => console.log(err))
    }

    useEffect(()=> {
        preload()
    }, [])

    return (
        <div>
            <Head>
                <title>HERA | COLLECTIONS</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div id="hero" className="hero" style={hero && hero.background_image ? {backgroundImage: `url(${hero.background_image})`} : {backgroundImage: `url(https://images.unsplash.com/photo-1550684376-efcbd6e3f031?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80)`}}>
                <section />
                {hero && <div className="hero_content">
                    <p className="hero_supertitle">MOVIE COLLECTION</p>
                    <h2 className="hero_title">{hero.name && hero.name.toUpperCase()}</h2>

                    <p className="hero_description">{shorten(hero.description)}</p>

                    <ActionBlock type="collection" media={hero.parts && hero.parts[0] && hero.parts[0]} />

                    <div className="hero_parts">
                        <PosterSlider medias={hero.parts} preload={true} />
                    </div>
                </div>}
            </div>

            <ErrorBoundary FallbackComponent={Fallback}>
                <MediaSlider medias={collections}/>
            </ErrorBoundary>
        </div>
    )
}

export default withAuth(Home)