import Head from "next/head"
import {getMovieByID} from "../../helpers/movieApiCalls"
import ActionBlock from "../../components/utils/ActionBlock"
import {shorten, withAuth} from "../../helpers/utilities"
import {getCookieToken} from "../../helpers/authApiCalls";

export async function getServerSideProps({ query, req, res }) {
    const token = getCookieToken(req, res)

    return getMovieByID(query.movieID, token).then(hero => {
        if (!hero || hero.error) {
            return {
                notFound: true,
            }
        }
        return {props: {hero}}
    })
}

const collection = ({ hero }) => {

    return (
        <div>
            <Head>
                <title>HERA | {hero.name}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div id="hero" className="hero" style={{backgroundImage: `url(${hero.background_image})`}}>
                <section/>
                <div className="hero_content">
                    <img className="hero_logo" src={hero.logo} alt=""/>
                    {!hero.logo && <h2 className="hero_title">{hero.name && hero.name.toUpperCase()}</h2>}
                    <p className="hero_subtitle">
                        {hero.genres && hero.genres[0] && hero.genres.map((genre, index) => (
                            <span key={index} className="subtitle_span">{genre.name}</span>
                        ))}
                        {hero.duration && <span className="subtitle_span">{hero.duration}</span>}
                        {hero.rating && <span className="subtitle_span">RATING {hero.rating}</span>}
                    </p>
                    <p className="hero_description">{shorten(hero.description)}</p>

                    <ActionBlock type="movie" media={hero} absolute={true}/>
                </div>
            </div>
        </div>
    )
}

export default withAuth(collection)